# Generated by Django 4.2.7 on 2026-06-04 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dept_id',
            field=models.ForeignKey(db_column='dept_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reporting_manager_id',
            field=models.ForeignKey(blank=True, db_column='reporting_manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.role'),
        ),
    ]
